baseurl: "http://www.gohugo.org"
languageCode: "en"
title: "Data Sciences"
#copyright: "Copyright © <a href=\"http://blog.coderzh.com/\">CoderZh</a> 2015."
theme: "hugo-org"

canonifyurls: true
RSSUri: "feed.xml"
MetaDataFormat: "yaml"
hasCJKLanguage: true

taxonomies:
  tag: "tags"
  category: "categories"
  doc: "doc"

params:
  Keywords: "Hugo, 博客, 中文, 文档, 皮肤, 示例, 搭建, 教程, 部署"
  Description: "Welcome to Data Sciences"
  analytics: "UA-10147768-3"
